# Generated by Django 5.0.6 on 2024-05-20 09:22

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contact_us'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='ecommerce/order/image')),
                ('quantity', models.CharField(default=1, max_length=100)),
                ('price', models.IntegerField(null=True)),
                ('address', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=15)),
                ('pincode', models.CharField(max_length=10)),
                ('total', models.CharField(max_length=150)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
